baseURL       = 'https://www.101loops.com/'
languageCode  = 'en-us'
title         = '101loops'
theme         = "introduction"
publishDir    = "docs"
canonifyURLs  = false

[security]
  [security.exec]
    osEnv = ['.*']

[languages]
    [languages.en]
        [languages.en.params]
            description  = "101loops"
            footerText   = "Cloud-based software development."
